version: '3'
services:
  scrape:
    build: ./news-scrape-exam/
    env_file:
      - .env
  api:
    build: ./news-api/
    env_file:
      - .env
  nginx:
    build: ./nginx/
    links:
      - api
    ports:
      - '80:80'
  rabbitmq:
    image: rabbitmq:latest